main: cn.wode490390.nukkit.signeditor.SignEditorPlugin
name: "SignsEditor"
author: "wode490390"
description: "Sign editor plugin for Nukkit"
website: "https://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.0"]
load: POSTWORLD

permissions:
  sign.command:
    description: "Allows a player to use /sign"
    default: op
